# Generated by Django 4.0.2 on 2022-02-16 04:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(choices=[('App', 'app'), ('API', 'api'), ('Design', 'design'), ('Server', 'server')], max_length=100)),
                ('page_no', models.CharField(blank=True, choices=[('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10')], max_length=100, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, default='app/default.jpg', null=True, upload_to='app/featured-image/')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('hasDoc', models.BooleanField(blank=True, default=False, null=True)),
                ('docname', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('origin_image', models.ImageField(blank=True, default='webapp/default-origin.jpg', null=True, upload_to='webapp/byte-art/')),
                ('style_image', models.ImageField(blank=True, default='webapp/default-style.jpg', null=True, upload_to='webapp/byte-art/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
